name: 'openfn deploy'
branding:
  icon: 'upload'
  color: 'purple'
description: 'Deploys a yaml file to a Lightning instance'
inputs:
  secret_input:
    description: "OpenFN API KEY"
    required: true
  config_path_input:
    description: "OpenFN Path to Config"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Project export
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: |
        npm install -g @openfn/cli
        openfn deploy -c $OPENFN_CONFIG_PATH --no-confirm
      shell: bash
      env: 
        OPENFN_API_KEY: ${{ inputs.secret_input }}
        OPENFN_CONFIG_PATH: ${{ inputs.config_path_input }}
    - name: Commit updated state file
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: Changes accepted by Lightning; updated current project state
